<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.9.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\fx_rate_service.proto" GrpcServices="Server" />
  </ItemGroup>

  <Choose>
    <When Condition=" '$(Configuration)'=='Release' ">
      <ItemGroup>
        <Content Include="export_chart.py">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
      </ItemGroup>
    </When>
  </Choose>

</Project>
